spring.application.name=API-GATEWAY

server.port=8080

# Eureka Server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Product Service Route

spring.cloud.gateway.server.webflux.routes[0].id=PRODUCT-SERVICE

spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/products/**



# Order Service Route

spring.cloud.gateway.server.webflux.routes[1].id=ORDER-SERVICE

spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDER-SERVICE

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**